version: "3.8"

services:
  caruna-influxdb-updater:
    image: vonlatvala/caruna-influxdb-updater
    environment:
      - TZ=Europe/Helsinki
      - INFLUX_HOST=
      - INFLUX_USERNAME=
      - INFLUX_PASSWORD=
      - INFLUX_DATABASE=
      - CARUNA_USERNAME=
      - CARUNA_PASSWORD=
    restart: unless-stopped
